name: eassist_tools_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.1.0
  
  accordion: ^2.6.0
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.2
  collection: ^1.18.0
  const_date_time: ^1.1.0
  date_field: ^6.0.0
  dropdown_search: ^6.0.1
  dio: ^5.4.0
  equatable: ^2.0.3
  file_picker: ^8.0.0+1
  flex_color_scheme: ^8.0.2
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2
  flutter_launcher_icons: ^0.14.2
  flutter_bloc: ^8.0.0
  flutter_slidable: ^3.1.2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.0+1
  foundation: ^0.0.5
  grouped_list: ^6.0.0
  http: ^1.2.1
  image: any
  image_picker: ^1.0.7
  intl: ^0.20.0
  introduction_screen: ^3.1.14
  mime: ^2.0.0
  meta: ^1.10.0
  open_filex: ^4.6.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  path_provider: ^2.0.11
  quick_input_formatters: ^0.0.4
  sqflite: ^2.3.1  
  string_validator: ^1.0.2
  uuid: ^4.5.1

flutter:
  uses-material-design: true
  assets:  
    - assets/images/
    - assets/images/month/
    - assets/icons/ 
    
  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf  

flutter_launcher_icons:
  image_path: "assets/images/logo_launcher.png"
  android: true
  ios: true  
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21